# Generated by Django 4.1.6 on 2023-02-21 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simulator', '0002_alter_portfolio_user_alter_trade_user_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='cost_basis',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='shares',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='stock',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='stock_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
