# Generated by Django 4.1.6 on 2023-02-23 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0003_remove_portfolio_cost_basis_remove_portfolio_shares_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
