# Generated by Django 4.1.6 on 2023-02-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0004_delete_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('PhoneNumber', models.IntegerField(max_length=12)),
                ('stock', models.CharField(default='', max_length=50)),
                ('stock_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cash', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
            ],
        ),
    ]
