# Generated by Django 4.1.6 on 2023-03-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0006_stock_user_trade_cost_alter_userdetails_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='stock',
            field=models.CharField(default='', max_length=50),
        ),
    ]
