# Generated by Django 4.1.6 on 2023-03-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0008_trade_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='PhoneNumber',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='stock',
        ),
        migrations.AddField(
            model_name='stock',
            name='username',
            field=models.CharField(default='kk', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='username',
            field=models.CharField(default='kk', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='username',
            field=models.CharField(default='kk', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=1000000, max_digits=10),
        ),
    ]
