# Generated by Django 4.1.6 on 2023-03-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0011_alter_userdetails_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='no_of_shares',
            field=models.IntegerField(default=0),
        ),
    ]
