# Generated by Django 4.1.6 on 2023-03-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0012_stock_no_of_shares'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
