# Generated by Django 4.1.6 on 2023-03-13 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0013_userdetails_profit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='price',
        ),
    ]
