# Generated by Django 4.1.6 on 2023-03-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author', models.CharField(max_length=50)),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.TextField(max_length=300)),
                ('ArticleImage', models.ImageField(upload_to='ArticleImage/')),
                ('active', models.BooleanField(default=True, null=True)),
                ('Date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
