# Generated by Django 4.1.6 on 2023-02-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_account_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=10),
        ),
        migrations.AddField(
            model_name='account',
            name='stock',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='stock_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=15),
        ),
    ]
