# Generated by Django 4.1.6 on 2023-02-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_cash_account_stock_account_stock_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='cash',
        ),
        migrations.RemoveField(
            model_name='account',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='account',
            name='stock_value',
        ),
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
